version: '3'

services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "7171:7171"
  auth:
    build: 
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    environment:
      JWT_SECRET: "VERYSTRONGSECRET"
      ACCESS_TIME_DURATION_MINUTES: 5
      REFRESH_TIME_DURATION_MINUTES: 20