version: '3'

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: dany
      POSTGRES_PASSWORD: 123abc

  db_auth:
    image: postgres:9.6
    environment:
      POSTGRES_DB: db_auth
      POSTGRES_USER: dany
      POSTGRES_PASSWORD: 123abc

  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "7171:7171"
    depends_on:
      - "db"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: dany
      DB_NAME: db
      DB_PASSWORD: 123abc

  rabbitmq:
    image: rabbitmq:management

  auth:
    build: 
      context: ./auth
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9191:9191"
    depends_on:
      - "db_auth"
      - "rabbitmq"
    environment:
      JWT_SECRET: "VERYSTRONGSECRET"
      ACCESS_TIME_DURATION_MINUTES: 5
      REFRESH_TIME_DURATION_MINUTES: 20
      DB_HOST: db_auth
      DB_PORT: 5432
      DB_USER: dany
      DB_NAME: db_auth
      DB_PASSWORD: 123abc

  sms:
    build: 
      context: ./sms
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - "rabbitmq"